tienda_enlinea/carts/urls.py
""" URLS del carrito de compras """


from django.urls import path
from . import views


app_name = 'carts'

urlpatterns = [
    
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove')
    
]

tienda_enlinea/tienda_enlinea/urls.py
""" General URL's."""

#Django
from django.contrib import admin
from django.urls import path
from django.urls import include

from django.conf.urls.static import static
from django.conf import settings


#Views
from . import views

#Models
from products.views import ProductListView

urlpatterns = [
    #vacio por que es la url de inicio
    path('',ProductListView.as_view(), name='index'), # udsando la clase ProductListView como una vista
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/registro', views.register, name='register'),
    path('admin/', admin.site.urls),
    
    # Declarando las URL's de la Aplicacion Productos
    path('productos/', include('products.urls')),
    
    # Declarando las URL's de la Aplicacion Carrito de compras
    path('carrito/', include('carts.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

tienda_enlinea/templates/base.html
{% load static%} <!-- todos los achivos que hereden de base podran acceder a los archivos estaticos -->
<!---->
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    
    </head>
    <body>

       <!-- llamando desde el template navbar.html-->
        {% include 'navbar.html '%}

        <div class="container">
        
        <!-- llamando desde el template messages.html-->
        {% include 'messages.html' %}
        
            <div class="row mt-5">

                {% block content %}
                {% endblock %}

            </div>
        </div>
    </body>
    <script src="https://kit.fontawesome.com/c26f95a2fa.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</html>

tienda_enlinea/templates/index.html
{% extends 'base.html'%}

{% block content %}
    <div class="col">
    <!-- usando la 'message' variable del contexto desde la vista-->
      <h4 class="text-center"> {{ message }}</h4>  
      
      <!-- Incluydendo la barra de-->
      {% include 'products/snippets/search.html'%}

      <!-- Mostrar la busaueda de elementos-->
      {% include 'products/snippets/list.html'%}

      </div>
    </div>
{% endblock %}
<!---->

tienda_enlinea/templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags == 'succes'%}alert-success{%else%}alert-danger{%endif%}">
            <button type="button" class="close" data-dismiss="alert">x</button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

tienda_enlinea/templates/navbar.html
<!-- generar variables para las urls-->

{% url 'login' as login %}
{% url 'register' as register %}
{% url 'carts:cart' as cart %}

<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <a href="#" class="navbar-left"><img src="/static/images/logo11.png" height="100"></a>

    <a href="{% url 'index' %}" class="navbar-brand">Skateboard Shop</a>

    <button type="button" name="button" class="navbar-toggler navbar-toggler-righ" data-toggle="collapse" data-target="#navb">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navb" class="navbar-collapse collapse hide">
      
        <ul class="navbar-nav">
          <!-- Is active para activar la URL-->
          <li class="nav-item {% if request.path == cart %}active{% endif %}">
            <a class="nav-link" href="{{ cart }}">
              Mi carrito <span class="fas fa-shopping-cart"></span>
            </a>
          </li>
        </ul>

        <ul class="nav navbar-nav ml-auto">

           <!-- saber si el usuario se encuentra autenticado o no , usando el Objeto user--> 
           {% if user.is_authenticated %} 
            <li class="navbar-item">
              <a href="{% url 'logout' %}" class="nav-link">Logout</a>
            </li>

           {% else %}   

            <li class="navbar-item {% if request.path == login %}active{% endif %}">
              <a href="{{ login }}" class="nav-link">
                <span class="fas fa-user"></span>
                  Login</a>

            </li>
            <li class="navbar-item {% if request.path == register %}active{% endif %}">
              <a href="{{ register }}" class="nav-link">Registro</a>
            </li>

           {% endif %}     
        </ul>
    </div>
</nav>