tienda_enlinea/carts/urls.py
""" URLS del carrito de compras """


from django.urls import path
from . import views


app_name = 'carts'

urlpatterns = [
    
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove')
    
]

tienda_enlinea/products/urls.py
""" URL's correspondientes a la Aplicacion Products. """

#Django
from django.urls import path

#Views 
from . import views

#Indicamos que pertenece a esta aplicacion
app_name = 'products'

urlpatterns = [
    
    # colocamos primero la URL de la busqueda de productos
    path('search', views.ProductSearchListView.as_view(), name="search"),
    
    # Vista que permite buscar desde el valor (q) en el queryset
    path('<slug:slug>', views.ProductDetailView.as_view(), name='product'),
    
]

tienda_enlinea/tienda_enlinea/urls.py
""" General URL's."""

#Django
from django.contrib import admin
from django.urls import path
from django.urls import include

from django.conf.urls.static import static
from django.conf import settings


#Views
from . import views

#Models
from products.views import ProductListView

urlpatterns = [
    #vacio por que es la url de inicio
    path('',ProductListView.as_view(), name='index'), # udsando la clase ProductListView como una vista
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/registro', views.register, name='register'),
    path('admin/', admin.site.urls),
    
    # Declarando las URL's de la Aplicacion Productos
    path('productos/', include('products.urls')),
    
    # Declarando las URL's de la Aplicacion Carrito de compras
    path('carrito/', include('carts.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

tienda_enlinea/carts/models.py
""" Modelo del carrito de compras """
import uuid
#Django
from django.db import models
from django.db.models.signals import pre_save

#Modelos
from users.models import User
from products.models import Product

# El carrito de compras tendra una relacion con el modelo User, de Uno a muchos
# No estara restringido que solo los usuarios autenticados puedan hacer su carrito de compras

class Cart(models.Model):
    #ForeignKey = establece una relacion, uno a muchos.
    #CASCADE =  indica que cuando se borre un usuario, tambien se eliminen sus relaciones.
     #cart_id = crea un identificador unico para cada sesion, string alfanumerico
     
    cart_id = models.CharField(max_length=100, null=False, blank=True, unique=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product)
    subtotal = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    total = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        # Identificador unico
        return self.cart_id
 
# Creando un indentificador unico para nuestro carrito de compras
# Esta funcion es un callback   
def set_cart_id(sender, instance, *args, **kwargs):
    #crear un carrito si y solo si no existe uno
    if not instance.cart_id:
        instance.cart_id = str(uuid.uuid4())
        
pre_save.connect(set_cart_id, sender=Cart)

tienda_enlinea/carts/views.py
""" Vista del carrito de compras """

#Django
from django.shortcuts import render
from django.shortcuts import redirect

#Modelos
from .models import Cart
from products.models import Product

#Utilidades
from .utils import get_or_create_cart


#funcion del carrito de compras
def cart(request):
    cart = get_or_create_cart(request)
    
    return render(request, 'carts/cart.html', {
        # Enviar el objeto cart al template, para visualizar los productos en el carrito 
        'cart':cart
    })

#funcion para agregar productos al carrito de compras    
def add(request):
    #obteniendo el carrito de compras
    cart = get_or_create_cart(request)
    product = Product.objects.get(pk=request.POST.get('product_id')) # product_id = llave
    
    #Agregar productos al carrito de compras(modelo cart posee una relacion a productos ManyToMany)
    cart.products.add(product)
    
    return render(request, 'carts/add.html', {
        #contexto
        'product':product
    })

# Funcion para eliminar productos del carrito de compras    
def remove(request):
    cart = get_or_create_cart(request)
    product = Product.objects.get(pk=request.POST.get('product_id'))
    
    # Seleccionamos el objeto a eliminar --> product
    cart.products.remove(product)
    
    return redirect('carts:cart')

tienda_enlinea/carts/templates/carts/add.html
{% extends 'base.html'%}

<!-- Incluyendo el archivo de product_extras-->
{% load product_extras %}

{% block content %}
    <div class="col-3">
        {% if product.image %}
            <img src="{{ product.image.url }}" alt="Imagen del producto" width="200" height="200">
        {% endif %}
    </div>

    <div class="col">
        <div class="h3 font-weight-bold text-success">
            Producto agregado al carrito de compras
        </div>
        <div class="">
            <a href="{% url 'products:product' product.slug %}">
                {{ product.title }}
            </a>
        </div>

        <!-- Incluyendo el filter-->
        <div class="font-weight-bold text-danger">
            {{ product.price | price_format }}
        </div>
    </div>
{% endblock %}

tienda_enlinea/carts/templates/carts/cart.html
<!-- Este template muestra los productos agregados en el carrito de compras-->

{% extends 'base.html' %}
{% load product_extras %}

{% block content %}

    {% if cart.products.exists %}
        <div class="col-8">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                        <th scope="col">Cantidad</th>
                        <th scope="col">Precio</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- all: obtener todos los productos que se encuentren en la relacion con el carrito de compras-->
                    {% for product in cart.products.all %}
                        <tr>
                            <th>{{ forloop.counter }}</th>
                            <th>
                                {% if product.image %}
                                    <img src="{{ product.image.url }}" alt="Imagen del producto" width="70" height="70">
                                {% endif %}
                            </th>
                            <th>
                                <a href="{% url 'products:product' product.slug %}">{{ product.title }}</a>

                                <!-- Incluyendo la opcion de borrar productos del carrito de compras -->
                                {% include 'carts/snippets/remove.html '%}
                            </th>
                            <th>1</th>
                            <th>
                                <span class="font-weight-bold text-danger">{{ product.price | price_format }}</span>
                            </th>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <div clas="col">
            <p class="h3">Tú carrito de compras está vacío.</p>
            <a href="{% url 'index' %}">Seguir comprando</a>
        </div>
    {% endif %}
{% endblock %}